# Generated by Django 4.1.2 on 2022-10-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='meetups.location'),
        ),
    ]
